### PR TITLE
Adds PHP 8.3 as new supported version

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by boesing** [comment]
Thanks, @fezfez.

Will see when I find some time to remove all changes besides `composer.json`.
There is no need to update psalm, especially not if you then add the issues to the baseline rather than fixing them.

So once I find some time, I will:
- remove dependency bumps
- remove psalm baseline change

If you find some time meanwhile, feel free to revert those changes so that we can merge this.

**Comment by fezfez** [comment]
> Thanks, @fezfez.
> 
> Will see when I find some time to remove all changes besides `composer.json`. There is no need to update psalm, especially not if you then add the issues to the baseline rather than fixing them.
> 
> So once I find some time, I will:
> 
>     * remove dependency bumps
> 
>     * remove psalm baseline change
> 
> 
> If you find some time meanwhile, feel free to revert those changes so that we can merge this.

i have clean some psalm error, if you agree i prefer moving forward instead of backward, i have left two error that i think can be easily cleaned with some knowledge that i don't have

**Comment by boesing** [comment]
> [...] i prefer moving forward instead of backward [...]

Its absolutely fine that you prefer going forward.
What I do try to avoid here is changes introduced in a PHP update which lead to BC breaks (i.e. by removing `return` statement and replace them with a totally different return value while ignoring the return value of the method which was invoked earlier).

Therefore, I will definitely remove these changes.
Focussing on the real topics mostly avoids accidentally introducing bugs. So unless something is necessary for PHP 8.3, please move those changes to dedicated PRs. Absolutely happy with receiving dedicated PR targeting psalm issues where we can discuss some changes, etc. - but I think that if we do not merge this, some1 will start crying once PHP 8.3 is out and badly wants this to be released.

---

Most of the psalm stuff cannot be changed anyways as almost any return types/property types are invalid starting in `laminas-cache`.

Since there will be a new major version for `laminas-cache` introducing 100% type-inference and which ill remove all those "pass by reference" stuff, which will then require a new major here as well, I do not see why we should spend time in fixing something which is somehow "accepted" by users.

We do have a bunch of stuff baselined regarding laminas, thats most likely since there was never a check if the types are *always* like they're stated (besides the fact that some1 added unit tests which only test happy-path). Therefore, we sadly have to live with the fact that psalm will report a bunch of stuff until we are able to fix these in new versions (sometimes even in majors as "making psalm happy" and "breaking stuff" is sometimes unavoidable).

**Comment by fezfez** [comment]
@boesing see https://github.com/laminas/laminas-cache-storage-adapter-filesystem/pull/75/files
but without adding to baseline the build fail...

i dont understand the main reason to not run baseline, i have done it in a lot of pull request

edit : see https://github.com/laminas/laminas-cache/pull/280/files as example

**Comment by nusphere** [comment]
#80

**Comment by Xerkus** [comment]
Superseded by #75

**Pull request closed without merging**
