### PR TITLE
Corrected link to documentation

### PR DESCRIPTION
**Pull request by modir**
related to issue #87

### CODE REVIEW

**Comment by boesing** [comment]
@froschdesign is there a way to target the most recent version with auto-redirect? Would this make sense?

**Comment by froschdesign** [comment]
@boesing 
Correct, remove the version number: https://docs.laminas.dev/laminas-cache/storage/adapter/#filesystem-adapter
Based on: https://github.com/laminas/laminas-cache/blob/7a0b59b1bb579becea82bf8fe69eb456dcdb2aaf/mkdocs.yml#L74-L77

**Comment by boesing** [comment]
when I click that link without version, I get redirected to v3 but v4 is available as well. That seems odd.

**Comment by gsteel** [comment]
There's old redirect maps that still point to v3 https://github.com/laminas/laminas-cache/blob/4.1.x/mkdocs.yml#L74-L86

**Comment by froschdesign** [comment]
The redirects must be updated with each major version.

**Review by boesing — APPROVED** [review]

**Comment by boesing** [comment]
I updated the link and reverted the text changes to align with the other adapters.
Thanks @modir

**Pull request merged**
