### PR TITLE
fix #25

### LINKED ISSUE #25: Not working with laminas/laminas-eventmanager:3.4
Hello,

I've update to ^2.0 but a got an issue

````
aminas\EventManager\EventManager::detach(): Argument #1 ($listener) must be of type callable, null given, called in /var/www/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php on line 115
````

The $listerne var is null instead of being a callable, see :

(https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/ad9d9d19abcdd36c8ccad370120cf5a97a610f80/src/Filesystem.php#L107-L117)

EventManagerInterface : 

https://github.com/laminas/laminas-eventmanager/blob/9e11e32de9eb66451ddaba81d282cccb9bbf245f/src/EventManagerInterface.php#L96-L106

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by boesing** [comment]
Thanks for this PR.
Could you also add a failing unit test so we can prevent this error for future development?
Thanks in advance.

Would also be great if you rebase against 2.0.x branch (I can do that as well but if you are working on it, that would be great).

**Comment by fezfez** [comment]
@boesing : done

**Review by boesing — APPROVED** [review]
LGTM.

I must admit, that I am not even aware of the functionality of this code. We are detaching a listener from the event handler, which is always `null`.
So there is absolutely no chance that this code has any impact.

I wonder if this could be removed.

When looking into the previous implementation, this was related to the `Filesystem#getTotalSpace` method and was to reset an already detected, cached, total space value for a preconfigured directory. Not sure if the `detach` logic provides anything useful - but this is just for the sake of completeness here. I will create an issue from this comment for further investigation and refactoring.

**Comment by boesing** [comment]
Thanks, @fezfez!

**Pull request merged**
