### PR TITLE
Update PHP 8.3 and package dependencies

### PR DESCRIPTION
**Pull request by nusphere**
This update modifies composer.json and composer.lock, specifically targeting the "PHP" and other package dependencies. These changes include the addition of PHP version "~8.3.0" to the range of compatible versions, as well as the various package upgrades and downgrades. This is necessary to keep the project updated with the latest compatible version of PHP and other software dependencies.

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

This PR allows to install this package with PHP 8.3. Since there is a dev requirement to ` laminas/laminas-cache-storage-adapter-benchmark` - laminas/laminas-cache-storage-adapter-benchmark#12 is required.

### CODE REVIEW

**Comment by nusphere** [comment]
@boesing why there is a composer platform requirement inside the composer.json ? The CI couldn't success until laminas/laminas-cache-storage-adapter-benchmark#12 is merged and a new tag (1.3.0) is done.

**Comment by Ocramius** [comment]
It's on purpose: we must have the `lockfile` pin to the lowest supported PHP version, or else you get all sorts of broken dependency upgrades.

We move that every time we drop an old PHP version

**Comment by nusphere** [comment]
#80

**Comment by Xerkus** [comment]
Duplicate of #75

**Pull request closed without merging**
